import { Router } from 'express';
import type sql from 'mssql';
import { SqlDatabase } from './shared/sql.js';
import { CatalogService } from './modules/catalogs/catalogs.js';
import { catalogRouter } from './modules/catalogs/router.js';
import { SqlCatalogRepository } from './modules/catalogs/sql-repository.js';
import { AccountService, assertLocalAuthAllowed } from './modules/accounts/service.js';
import { SqlAccountRepository } from './modules/accounts/sql-repository.js';
import { ScryptPasswords, secureTokens } from './modules/accounts/crypto.js';
import { accountRouter, sessionMiddleware } from './modules/accounts/router.js';
import { runtime } from './shared/ports.js';
import { PublicationService } from './modules/publications/service.js';
import { SqlPublicationRepository } from './modules/publications/sql-repository.js';
import { publicationRouter } from './modules/publications/router.js';
import { wallRouter } from './modules/publications/wall-router.js';
import { ContactService } from './modules/contact/service.js';
import { SqlContactRepository } from './modules/contact/sql-repository.js';
import { contactRouter } from './modules/contact/router.js';
import { ContributionService } from './modules/contributions/service.js';
import { SqlContributionRepository } from './modules/contributions/sql-repository.js';
import { contributionRouter } from './modules/contributions/router.js';
import { ModerationService } from './modules/moderation/service.js';
import { SqlReportRepository } from './modules/moderation/sql-repository.js';
import { moderationRouter } from './modules/moderation/router.js';
import { AdminService } from './modules/moderation/admin-service.js';
import { SqlAdminRepository } from './modules/moderation/admin-sql-repository.js';
import { adminRouter } from './modules/moderation/admin-router.js';
export function createApi(pool: sql.ConnectionPool) {
  assertLocalAuthAllowed(process.env);
  const db = new SqlDatabase(pool);
  const catalogs = new CatalogService(new SqlCatalogRepository(db));
  const router = Router();
  router.use(catalogRouter(catalogs));
  const accounts = new AccountService(new SqlAccountRepository(db), new ScryptPasswords(), secureTokens, runtime, catalogs);
  router.use(sessionMiddleware(accounts));
  router.use(accountRouter(accounts, process.env.COOKIE_SECURE === 'true'));
  const publicationRepository = new SqlPublicationRepository(db);
  const publications = new PublicationService(publicationRepository, catalogs, runtime);
  router.use(publicationRouter(publications));
  router.use(wallRouter(publications));
  router.use(contactRouter(new ContactService(new SqlContactRepository(db), runtime)));
  router.use(contributionRouter(new ContributionService(new SqlContributionRepository(db), publicationRepository, catalogs, runtime, secureTokens.hash)));
  router.use(moderationRouter(new ModerationService(new SqlReportRepository(db), catalogs, runtime)));
  router.use(adminRouter(new AdminService(new SqlAdminRepository(db), new SqlCatalogRepository(db))));
  return router;
}
